name: Build & Test Packages - Nix - Ubuntu

on:
  pull_request:
  push:
    branches: [kilted]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_test_packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.3

      - uses: cachix/install-nix-action@v31.10.6
        with:
          extra_nix_config: |
            accept-flake-config = true

      - uses: cachix/cachix-action@v17
        with:
          name: spikonado
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build and Cache Shell Environment
        run: |
          nix develop --profile variobot-shell -c true
          cachix push spikonado variobot-shell

      - name: Build Packages
        shell: 'nix develop --profile variobot-shell -c bash -e {0}'
        run: colcon build --event-handlers=console_cohesion+ --symlink-install

      - name: Test Packages
        shell: 'nix develop --profile variobot-shell -c bash -e {0}'
        run: |
          colcon test --event-handlers=console_direct+
          colcon test-result --all
          colcon test-result --verbose

      - name: Run fmt
        shell: 'nix develop --profile variobot-shell -c bash -e {0}'
        run: nix fmt
