name: MCU CI

on:
  merge_group:
  pull_request:
    paths:
      - .github/workflows/mcu-ci.yml
      - variobot_mcu/**
  push:
    branches: [kilted]
  workflow_dispatch:

permissions:
  contents: read

defaults:
  run:
    working-directory: variobot_mcu

jobs:
  mcu_ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2

      - uses: cachix/install-nix-action@v31.10.1
        with:
          extra_nix_config: |
            accept-flake-config = true

      - uses: cachix/cachix-action@v14
        with:
          name: spikonado
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build and Cache Shell Environment
        run: |
          nix develop --profile variobot-mcu-shell -c true
          cachix push spikonado variobot-mcu-shell

      - name: Build Firmware
        shell: 'nix develop --profile variobot-mcu-shell -c bash -e {0}'
        run: |
          idf.py build
