name: Prek

on:
  merge_group:
  pull_request:
  push:
    branches: [kilted]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run_prek:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false

      - uses: cachix/install-nix-action@v31.11.1
        with:
          extra_nix_config: |
            accept-flake-config = true

      - uses: cachix/cachix-action@v17
        with:
          name: spikonado
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build and Cache Shell Environment
        run: |
          nix develop --profile variobot-shell -c true
          cachix push spikonado variobot-shell

      - name: Run prek
        shell: 'nix develop --profile variobot-shell -c bash -e {0}'
        run: prek run -a
